# Generated by Django 3.1.7 on 2021-06-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerFirstName', models.CharField(max_length=20, null=True)),
                ('customerLastName', models.CharField(max_length=20, null=True)),
                ('customerAddress', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
