# Generated by Django 3.1.7 on 2021-06-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customerAddress',
            new_name='c_address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customerFirstName',
            new_name='c_first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customerLastName',
            new_name='c_last_name',
        ),
    ]
