# Generated by Django 3.1.7 on 2021-06-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210606_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='c_first_name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='c_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='c_last_name',
            new_name='lastName',
        ),
    ]
