# Generated by Django 3.1.7 on 2021-04-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=200)),
                ('contact_no', models.CharField(max_length=10)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
    ]
