# Generated by Django 3.1.7 on 2021-04-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210411_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='id',
        ),
        migrations.AlterField(
            model_name='messages',
            name='name',
            field=models.CharField(blank=True, max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
