# Generated by Django 3.1.7 on 2021-04-09 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_awards_education_experience_interest_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='achievement',
            new_name='hobbies',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='certificate',
            new_name='workingField',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='place',
        ),
    ]
