# Generated by Django 3.1.7 on 2021-04-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210409_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awards',
            old_name='participation',
            new_name='achievements',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='workingField',
            new_name='Languages',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='workDate',
        ),
        migrations.AddField(
            model_name='education',
            name='faculty',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='workDateFrom',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='workDateFrom',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='workDateTo',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='hobbiesDes',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='workPosition',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='hobbies',
            field=models.CharField(max_length=200),
        ),
    ]
